config/routes.rb
Rails.application.routes.draw do
  root 'songs#index'
  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end 

  def create
    Song.create(song_params)
    redirect_to root_path
  end

  private

  def song_params
    params.require(:song).permit(:firstdance, :artist)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class="col-3">
       <%= link_to root_path, class: 'logo' do %>
        <div class="circle">
         <br />
         WEDDINGCO
         <br />
         MUSIC
         <br />
       </div>
       <% end %>
      </div>
      <div class="col-4">
        Top songs for your special wedding dance
      </div>
      <div class="col-5">
        <%= link_to 'Contribute', new_song_path %>
      </div>
    </header>

    <hr />

    <br class="clear">

    <%= yield %>

  </body>
</html>

app/views/songs/index.html.erb
<% @songs.each do |song| %>
 <div>
    <h1><%= song.firstdance %></h1><br />
    <i><%= song.artist %></i><br />
  </div>

  <hr />

<% end %>

app/views/songs/new.html.erb
<h1>Enter Your Song</h1>
<%= simple_form_for @song do |f| %>
  <%= f.input :firstdance %>
  <%= f.input :artist %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>

app/views/static_pages/index.html.erb
<h1><%= @song.firstdance %></h1>
<br />
<h2><%= @song.artist %></h2>